apiVersion: v2
description: Mattermost Team Edition server.
type: application
name: mattermost-team-edition
version: 6.6.83
appVersion: 10.11.2
kubeVersion: ">=1.20.0"
keywords:
  - mattermost
  - communication
  - team collaboration
home: https://mattermost.com
icon: http://www.mattermost.org/wp-content/uploads/2016/04/icon.png
sources:
  - https://github.com/mattermost/mattermost-server
  - https://github.com/mattermost/mattermost-helm
maintainers:
    - name: Maximiliano Pizarro
      email: maximiliano.pizarro.5@gmail.com
      url: http://www.linkedin.com/in/maximiliano-gregorio-pizarro-consultor-it
dependencies:
  - name: mysql
    version: 1.6.4
    repository: https://charts.helm.sh/stable
    condition: mysql.enabled

annotations:
  charts.openshift.io/name: mattermost